server:
  port: 8081
spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost/mybatis
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule # 负载均衡规则
ribbon:
  eager-load:
    enabled: true # 开启 饥饿加载模式
    clients: 
      - userservice # set this userservice use hangrag load

#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/